### ISSUE TITLE
Images aren't available

### ISSUE THREAD

**Issue by thedhrub0** [zalandoresearch/feidegger#3]
Images aren't available. I'm seeing this message: 

```The image “https://i2.ztat.net/large/Y0/32/1C/00/UE/11/Y0321C00U-E11@10.jpg” cannot be displayed because it contains errors.```

**Comment by yosipk** [comment]
Hi @thedhrub0, thank you for raising this issue. We've updated the image links, just be aware that the file is now called [FEIDEGGER_release_1.2.json](https://github.com/zalandoresearch/feidegger/blob/master/data/FEIDEGGER_release_1.2.json).
